# rust-analyzer can be configured with nightly rustfmt
# i.e. for vscode in settings.json:
#    "rust-analyzer.rustfmt.extraArgs": [
#        "+nightly"
#    ],
edition = "2024"
unstable_features = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = false
comment_width = 100
wrap_comments = true
newline_style = "Unix"
use_field_init_shorthand = true
